typography_spectrum: 0.5707955844700336
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.4732717687729746
  lightness: 0.15386186982505023
  saturation: 0.12450387747958302
  rhythmicContrast: 0.7135077556595206
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7644222374074161
analytics:
  google: null
  facebook: null
  twitter: null
name: Kelly Kruschel
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Facebook
    url: 'http://www.facebook.com'
    type: external
favicon: null
title: ereh si leoJ
description: hahahahah
purpose: []
