name: Kelly Kruschel
favicon: null
layout_spectrum: 0.6319033964537084
typography_spectrum: 0.8258801340125501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.23837373428978026
  lightness: 0.0165019144769758
  saturation: 0.4750635679811239
  rhythmicContrast: 0.6275969527196139
purpose: []
